export default [
  {
    id: 'rpc01',
    name: 'Kronos',
    type: 'blaster',
    series: 'Rival',
    price: 55,
    description: '',
    color: 'phantomCorps',
    capacity: 5,
    images: [
      '/assets/images/products/rpc01/01.jpg ',
    ],
    firingMechanism: 'Spring-powered',
    priming: 'Manual',
    loading: 'Internal Magazine',
  },
  {
    id: 'rpc04',
    name: 'Helios',
    type: 'blaster',
    series: 'Rival',
    price: 89,
    description: '',
    color: 'phantomCorps',
    capacity: 7,
    images: [
      '/assets/images/products/rpc04/01.jpg ',
    ],
    firingMechanism: 'Spring-powered',
    priming: 'Manual',
    loading: 'External Magazine',
  },
  {
    id: 'rpc02',
    name: 'Hades',
    type: 'blaster',
    series: 'Rival',
    price: 159,
    description: '',
    color: 'phantomCorps',
    capacity: 60,
    images: [
      '/assets/images/products/rpc02/01.jpg ',
    ],
    firingMechanism: 'Spring-powered',
    priming: 'Manual',
    loading: 'Internal Magazine',
  },
  {
    id: 'rpc03',
    name: 'Hera',
    type: 'blaster',
    series: 'Rival',
    price: 149,
    description: '',
    color: 'phantomCorps',
    capacity: 12,
    images: [
      '/assets/images/products/rpc03/01.jpg ',
    ],
    firingMechanism: 'Motorised',
    priming: 'Semi-Automatic',
    loading: 'External Magazine',
  },
  {
    id: 'rb01',
    name: 'Nemesis',
    type: 'blaster',
    series: 'Rival',
    price: 219,
    description: '',
    color: 'blue',
    capacity: 100,
    images: [
      '/assets/images/products/rb01/01.jpg ',
    ],
    firingMechanism: 'Motorised',
    priming: 'Full-Automatic',
    loading: 'Hopper-fed',
  },
  {
    id: 'rr01',
    name: 'Zeus',
    type: 'blaster',
    series: 'Rival',
    price: 119,
    description: '',
    color: 'red',
    capacity: 12,
    images: [
      '/assets/images/products/rr01/01.jpg ',
    ],
    firingMechanism: 'Motorised',
    priming: 'Semi-Automatic',
    loading: 'External Magazine',
  },
];
