export const PRODUCT_LISTING_UPDATED = 'PRODUCT_LISTING_UPDATED';
export const PRODUCT_DESELECTED = 'PRODUCT_DESELECTED';
export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';

export const ADDED_PRODUCT_TO_CART = 'ADDED_PRODUCT_TO_CART';
export const CART_PRODUCT_QTY_UPDATED = 'CART_PRODUCT_QTY_UPDATED';
export const CART_EMPTIED = 'CART_EMPTIED';
export const MARKED_PRODUCT_FOR_REMOVAL = 'MARKED_PRODUCT_FOR_REMOVAL';
export const REMOVED_PRODUCT_FROM_CART = 'REMOVED_PRODUCT_FROM_CART';
export const SUBTOTAL_UPDATED = 'SUBTOTAL_UPDATED';

export const NAV_CART_POPOVER_SHOWN = 'NAV_CART_POPOVER_SHOWN';
export const NAV_CART_POPOVER_HIDDEN = 'NAV_CART_POPOVER_HIDDEN';
export const NAV_DRAWER_SHOWN = 'NAV_DRAWER_SHOWN';
export const NAV_DRAWER_HIDDEN = 'NAV_DRAWER_HIDDEN';

export const BILLING_FORM_UPDATED = 'BILLING_FORM_UPDATED';
export const CONTACT_DETAILS_UPDATED = 'CONTACT_DETAILS_UPDATED';
export const SHIPPING_FORM_UPDATED = 'SHIPPING_FORM_UPDATED';

export const ORDER_CREATED = 'ORDER_CREATED';
export const ORDER_FETCHED = 'ORDER_FETCHED';

export const CART_POPOVER_AUTOHIDE_DURATION = 3000;
